In [27]:
import numpy as np

!mkdir DATA

mkdir: cannot create directory ‘DATA’: File exists


In [32]:
# random seed for reproducibility
np.random.seed(12345)
print("random numbers from seed 12345:",np.random.random(4))
    
# number of data
N=10000
# 4 intervals of length Z=L/4, each containing a set of 1's or 0's
Z=4
# size of each data point
L=Z*4
# choose among states (1,0,1,0), (0,1,1,0), (1,0,0,1), (0,1,0,1) 
# from a 2x2 product of (1,0)x(1,0), with prob=1/4
# then
# Noise: switch each of L bits with probability q
q=0.3

x,y = np.zeros((N,L)),np.zeros(N)
vec1 = np.ones(Z)  

def ones(n,i,j):
    x[n][Z*i:Z*(i+1)] = vec1
    x[n][2*Z+Z*j:2*Z+Z*(j+1)] = vec1
    
for n in range(N):
    a = np.random.randint(0,2)
    b = np.random.randint(0,2)
    y[n] = a+b*2
    ones(n,a,b)
    
    for j in range(L):
        if np.random.random()<q:
             x[n][j] = 1-x[n][j]
                
x,y = x.astype(int),y.astype(int)

for n in range(min(12,N)):
    print(x[n],y[n])
print("...")
    
np.savetxt('DATA/x_RBM_q'+str(q)+'.dat',x,delimiter=" ",fmt="%d")
np.savetxt('DATA/y_RBM_q'+str(q)+'.dat',y,fmt="%d")

random numbers from seed 12345: [0.92961609 0.31637555 0.18391881 0.20456028]
[0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0] 1
[1 1 1 1 0 0 0 1 1 0 0 1 1 1 1 0] 2
[1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 0] 0
[0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0] 1
[1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1] 2
[0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1] 3
[1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0] 2
[0 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1] 1
[1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 0] 0
[0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 1] 2
[1 1 1 1 1 1 0 0 0 0 1 0 0 0 1 0] 0
[0 0 1 0 1 0 1 0 1 1 1 1 0 1 0 0] 0
...
